export const GET_KISI_SUCCESS="GET_KISI_SUCCESS";
export const GET_KISILER_SUCCESS="GET_KISILER_SUCCESS";
export const DELETE_KISI_SUCCESS="DELETE_KISI_SUCCESS";
export const ADD_KISI_SUCCESS="ADD_KISI_SUCCESS";
export const UPDATE_KISI_SUCCESS="UPDATE_KISI_SUCCESS";